# openbb_tushare

Check openbb_tushare version

In [1]:
import os
from dotenv import load_dotenv
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "tushare" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600325.SH"
symbol_hk = "01658"
provider = "tushare"
start_date="2025-05-01"
end_date="2025-05-27"
start_date_ts="20250501"
end_date_ts="20250527"

os.environ["TUSHARE_API_KEY"] = obb.user.credentials.tushare_api_key.get_secret_value()
load_dotenv() 
tushare_api_key = os.environ.get("TUSHARE_API_KEY")
if tushare_api_key is None:
    raise ValueError("TUSHARE_API_KEY environment variable not set.")

['tushare@1.2.0']

## 1. 股票相关模型 (Equity Models)
### 1.1 Equity Historical Price (股票历史价格)

In [13]:
obb.equity.price.historical(symbol=symbol_a, provider=provider, use_cache=True, start_date=start_date, end_date=end_date).to_dataframe().tail()

2026-05-05 11:00:54,313 - openbb_tushare.utils.ts_equity_historical - INFO - Getting equity 600325.SH historical data from cache...

,open,high,low,close,volume,amount,change,change_percent,pre_close
date,,,,,,,,,
2025-05-21,5.09,5.10,5.06,5.08,118539.51,60220.808,-0.01,-0.1965,5.09
2025-05-22,5.07,5.08,5.03,5.05,153842.60,77733.444,-0.03,-0.5906,5.08
2025-05-23,5.04,5.07,5.00,5.00,167287.00,84219.338,-0.05,-0.9901,5.05
2025-05-26,4.91,4.97,4.89,4.91,219101.71,107809.653,0.01,0.2041,4.90
2025-05-27,4.92,4.92,4.88,4.90,187843.06,92027.566,-0.01,-0.2037,4.91

In [3]:
import tushare as ts
pro = ts.pro_api(tushare_api_key)
df_data = pro.daily(ts_code=symbol_a, start_date=start_date_ts, end_date=end_date_ts)
df_data = df_data.sort_values('trade_date')
df_data.tail(11)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
10,600325.SH,20250513,5.11,5.12,5.06,5.08,5.09,-0.01,-0.1965,262377.76,133449.108
9,600325.SH,20250514,5.08,5.13,5.04,5.09,5.08,0.01,0.1969,318037.33,161534.496
8,600325.SH,20250515,5.09,5.10,5.04,5.05,5.09,-0.04,-0.7859,216004.96,109434.338
7,600325.SH,20250516,5.06,5.06,5.01,5.02,5.05,-0.03,-0.5941,216319.65,108760.642
6,600325.SH,20250519,5.02,5.07,5.00,5.07,5.02,0.05,0.9960,293509.24,148015.309
5,600325.SH,20250520,5.08,5.11,5.05,5.09,5.07,0.02,0.3945,196020.51,99611.576
4,600325.SH,20250521,5.09,5.10,5.06,5.08,5.09,-0.01,-0.1965,118539.51,60220.808
3,600325.SH,20250522,5.07,5.08,5.03,5.05,5.08,-0.03,-0.5906,153842.60,77733.444
2,600325.SH,20250523,5.04,5.07,5.00,5.00,5.05,-0.05,-0.9901,167287.00,84219.338
1,600325.SH,20250526,4.91,4.97,4.89,4.91,4.90,0.01,0.2041,219101.71,107809.653
0,600325.SH,20250527,4.92,4.92,4.88,4.90,4.91,-0.01,-0.2037,187843.06,92027.566

#### 前复权行情

In [4]:
qfq_df = ts.pro_bar(ts_code=symbol_a, adj='qfq', start_date=start_date_ts, end_date=end_date_ts)
qfq_df = qfq_df.sort_values('trade_date')
qfq_df.tail(11)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
10,600325.SH,20250513,5.01,5.02,4.96,4.98,4.99,-0.01,-0.20,262377.76,133449.108
9,600325.SH,20250514,4.98,5.03,4.94,4.99,4.98,0.01,0.20,318037.33,161534.496
8,600325.SH,20250515,4.99,5.00,4.94,4.95,4.99,-0.04,-0.80,216004.96,109434.338
7,600325.SH,20250516,4.96,4.96,4.91,4.92,4.95,-0.03,-0.61,216319.65,108760.642
6,600325.SH,20250519,4.92,4.97,4.90,4.97,4.92,0.05,1.02,293509.24,148015.309
5,600325.SH,20250520,4.98,5.01,4.95,4.99,4.97,0.02,0.40,196020.51,99611.576
4,600325.SH,20250521,4.99,5.00,4.96,4.98,4.99,-0.01,-0.20,118539.51,60220.808
3,600325.SH,20250522,4.97,4.98,4.93,4.95,4.98,-0.03,-0.60,153842.60,77733.444
2,600325.SH,20250523,4.94,4.97,4.90,4.90,4.95,-0.05,-1.01,167287.00,84219.338
1,600325.SH,20250526,4.91,4.97,4.89,4.91,4.90,0.01,0.20,219101.71,107809.653
0,600325.SH,20250527,4.92,4.92,4.88,4.90,4.91,-0.01,-0.20,187843.06,92027.566

#### 后复权行情

In [5]:
hfq_df = ts.pro_bar(ts_code=symbol_a, adj='hfq', start_date=start_date_ts, end_date=end_date_ts)
hfq_df = hfq_df.sort_values('trade_date')
hfq_df.tail(11)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
10,600325.SH,20250513,57.89,58.00,57.32,57.55,57.66,-0.11,-0.19,262377.76,133449.108
9,600325.SH,20250514,57.55,58.11,57.09,57.66,57.55,0.11,0.19,318037.33,161534.496
8,600325.SH,20250515,57.66,57.77,57.09,57.21,57.66,-0.45,-0.78,216004.96,109434.338
7,600325.SH,20250516,57.32,57.32,56.75,56.87,57.21,-0.34,-0.59,216319.65,108760.642
6,600325.SH,20250519,56.87,57.43,56.64,57.43,56.87,0.56,0.98,293509.24,148015.309
5,600325.SH,20250520,57.55,57.89,57.21,57.66,57.43,0.23,0.40,196020.51,99611.576
4,600325.SH,20250521,57.66,57.77,57.32,57.55,57.66,-0.11,-0.19,118539.51,60220.808
3,600325.SH,20250522,57.43,57.55,56.98,57.21,57.55,-0.34,-0.59,153842.60,77733.444
2,600325.SH,20250523,57.09,57.43,56.64,56.64,57.21,-0.57,-1.00,167287.00,84219.338
1,600325.SH,20250526,56.76,57.45,56.52,56.76,56.64,0.12,0.21,219101.71,107809.653
0,600325.SH,20250527,56.87,56.87,56.41,56.64,56.76,-0.12,-0.21,187843.06,92027.566

### 1.2 Equity Quote (股票实时报价)

In [2]:
obb.equity.price.quote(symbols, provider=provider).to_dataframe().head()

2026-04-22 14:02:04,179 - openbb_tushare.utils.ts_equity_quote - INFO - Getting equity quote data for 601919.SH...
2026-04-22 14:02:04,181 - openbb_tushare.utils.ts_equity_quote - INFO - Normalized symbol: base=601919, full=601919.SH, market=SH
2026-04-22 14:02:04,284 - openbb_tushare.utils.ts_equity_quote - INFO - Calling ts.realtime_quote(601919.SH)
2026-04-22 14:02:04,461 - openbb_tushare.utils.ts_equity_quote - INFO - Received data with columns: ['NAME', 'TS_CODE', 'DATE', 'TIME', 'OPEN', 'PRE_CLOSE', 'PRICE', 'HIGH', 'LOW', 'BID', 'ASK', 'VOLUME', 'AMOUNT', 'B1_V', 'B1_P', 'B2_V', 'B2_P', 'B3_V', 'B3_P', 'B4_V', 'B4_P', 'B5_V', 'B5_P', 'A1_V', 'A1_P', 'A2_V', 'A2_P', 'A3_V', 'A3_P', 'A4_V', 'A4_P', 'A5_V', 'A5_P']
2026-04-22 14:02:04,463 - openbb_tushare.utils.ts_equity_quote - INFO - Getting equity quote data for 600519.SH...
2026-04-22 14:02:04,464 - openbb_tushare.utils.ts_equity_quote - INFO - Normalized symbol: base=600519, full=600519.SH, market=SH
2026-04-22 14:02:04,465 - openbb_tushare.utils.ts_equity_quote - INFO - Calling ts.realtime_quote(600519.SH)
2026-04-22 14:02:04,592 - openbb_tushare.utils.ts_equity_quote - INFO - Received data with columns: ['NAME', 'TS_CODE', 'DATE', 'TIME', 'OPEN', 'PRE_CLOSE', 'PRICE', 'HIGH', 'LOW', 'BID', 'ASK', 'VOLUME', 'AMOUNT', 'B1_V', 'B1_P', 'B2_V', 'B2_P', 'B3_V', 'B3_P', 'B4_V', 'B4_P', 'B5_V', 'B5_P', 'A1_V', 'A1_P', 'A2_V', 'A2_P', 'A3_V', 'A3_P', 'A4_V', 'A4_P', 'A5_V', 'A5_P']
2026-04-22 14:02:04,596 - openbb_tushare.utils.ts_equity_quote - INFO - Getting equity quote data for 000001.SZ...
2026-04-22 14:02:04,597 - openbb_tushare.utils.ts_equity_quote - INFO - Normalized symbol: base=000001, full=000001.SZ, market=SZ
2026-04-22 14:02:04,598 - openbb_tushare.utils.ts_equity_quote - INFO - Calling ts.realtime_quote(000001.SZ)
2026-04-22 14:02:04,730 - openbb_tushare.utils.ts_equity_quote - INFO - Received data with columns: ['NAME', 'TS_CODE', 'DATE', 'TIME', 'OPEN', 'PRE_CLOSE', 'PRICE', 'HIGH', 'LOW', 'BID', 'ASK', 'VOLUME', 'AMOUNT', 'B1_V', 'B1_P', 'B2_V', 'B2_P', 'B3_V', 'B3_P', 'B4_V', 'B4_P', 'B5_V', 'B5_P', 'A1_V', 'A1_P', 'A2_V', 'A2_P', 'A3_V', 'A3_P', 'A4_V', 'A4_P', 'A5_V', 'A5_P']
2026-04-22 14:02:04,731 - openbb_tushare.utils.ts_equity_quote - INFO - Getting equity quote data for 00300.HK...
2026-04-22 14:02:04,732 - openbb_tushare.utils.ts_equity_quote - INFO - Normalized symbol: base=00300, full=00300.HK, market=HK
2026-04-22 14:02:04,732 - openbb_tushare.utils.ts_equity_quote - INFO - Calling pro.rt_hk_k(00300.HK)
2026-04-22 14:02:04,864 - openbb_tushare.models.equity_quote - ERROR - Error fetching data for symbol 00300.HK: 必填参数, ts_code

,symbol,name,bid,ask,last_price,open,high,low,volume,prev_close
0,601919.SH,中远海控,14.46,14.47,14.46,14.60,14.61,14.43,48187502,14.62
1,600519.SH,贵州茅台,1406.33,1406.45,1406.35,1415.00,1419.00,1404.98,2049819,1412.01
2,000001.SZ,平安银行,10.96,10.97,10.97,11.08,11.09,10.95,61608293,11.08

### 1.4 Equity Search (股票搜索)

In [4]:
obb.equity.search(query="", provider=provider).to_dataframe()

2026-03-10 16:59:36,686 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...

      symbol         name exchange
0     000001         平安银行     SZSE
1     000002        万  科Ａ     SZSE
2     000004        *ST国华     SZSE
3     000006         深振业Ａ     SZSE
4     000007          全新好     SZSE
...      ...          ...      ...
9990   00059         天誉置业     HKEX
9991   00039        中国北大荒     HKEX
9992   00033  INTL GENIUS     HKEX
9993   00009         金奥国际     HKEX
9994   00007       智富资源投资     HKEX

[9995 rows x 3 columns]

### 1.5 Equity Screener (股票筛选器)
因为下载数据较多，这个功能容易出现数据下载问题

In [5]:
obb.equity.screener(provider=provider).to_dataframe().head()

2026-02-04 15:57:27,363 - openbb_akshare.utils.fetch_quote - INFO - Generating new data...

OpenBBError:
[Unexpected Error] -> ProxyError -> HTTPSConnectionPool(host='72.push2.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=100&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f12&fs=m%3A128+t%3A3%2Cm%3A128+t%3A4%2Cm%3A128+t%3A1%2Cm%3A128+t%3A2&fields=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6%2Cf7%2Cf8%2Cf9%2Cf10%2Cf12%2Cf13%2Cf14%2Cf15%2Cf16%2Cf17%2Cf18%2Cf20%2Cf21%2Cf23%2Cf24%2Cf25%2Cf22%2Cf11%2Cf62%2Cf128%2Cf136%2Cf115%2Cf152 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

### 1.6 Equity Profile (股权资料)

In [3]:
obb.equity.profile(symbol="00005", provider='akshare', use_cache=True).to_dataframe().tail()

,symbol,name,ceo,company_url,business_address,mailing_address,business_phone_no,employees,industry_category,公司名称,公司简介,主要范围,上市日期,org_short_name_cn,org_short_name_en,org_id,actual_issue_vol,reg_asset,currency,成立日期
0,00005.HK,HSBC Holdings plc,利伯特,http://www.hsbc.com,"42nd Floor, 8 Canada Square, London United Kin...",香港中环皇后大道中1号,(852) 2822-1111,0,3.0,汇丰控股有限公司,"滙丰总部设於伦敦,是世界上规模最大的银行及金融服务机构之一。滙丰集团之国际网络横跨全...",提供全面之银行及有关之金融服务。国际网络遍布亚太区、欧洲、美洲、中东及非洲。,1988-12-29,,,200077073.0,0,0.0,HKD,1958-12-31 16:00:00

### 1.7 Historical Dividends (历史分红)

In [6]:
obb.equity.fundamental.dividends(symbol=symbol_a, provider=provider, use_cache=False).to_dataframe().head()

2026-02-04 15:57:47,568 - openbb_akshare.models.historical_dividends - INFO - Transformed historical dividends completed.

  ex_dividend_date  amount    description record_date report_date
0       2005-04-18    0.10      10派1元(含税)  2005-04-15  2005-04-12
1       2005-10-28    0.00         10转增3股  2005-10-27  2005-10-22
2       2006-04-07    0.10      10派1元(含税)  2006-04-06  2006-04-01
3       2008-02-27    0.10  10转10股派1元(含税)  2008-02-26  2008-02-21
4       2009-04-02    0.11    10派1.1元(含税)  2009-04-01  2009-03-26

## 2. 财务报表模型 (Financial Statement Models)
### 2.1 Balance Sheet (资产负债表)

In [7]:
obb.equity.fundamental.balance(symbol=symbol_hk, period="annual", limit=5,provider=provider).to_dataframe().head()

2026-02-04 15:57:51,214 - openbb_akshare.models.balance_sheet - INFO - Fetching balance sheet data for 01658 with limit 5 and use_cache=True
2026-02-04 15:57:51,217 - mysharelib.blob_cache - INFO - Loaded cached annual data with length 4 and limit is 5
2026-02-04 15:57:51,218 - mysharelib.blob_cache - INFO - Generating new annual data for 01658...
2026-02-04 15:57:51,235 - openbb_akshare.models.balance_sheet - INFO - Getting balance sheet data for 01658 with limit 5
2026-02-04 15:57:51,236 - openbb_akshare.utils.ak_balance_sheet - INFO - Fetching HK balance sheet for 01658 with limit 5 and period annual

,period_ending,总资产,买入返售金融资产,以公允价值计量的金融资产,优先股,保留溢利(累计亏损),公积金,其他储备,卖出回购金融资产,向中央银行借款,...,衍生金融工具-负债,衍生金融工具-资产,负债其他项目,资产其他项目,递延税项负债,递延税项资产,银行同业及其他金融机构存款(负债),银行同业及其他金融机构存款(资产),非控股股东权益,非运算项目
0,2024-12-31,1.708491e+13,2.298420e+11,6.004127e+12,NaN,2.633430e+11,1.626810e+11,3.044980e+11,1.945240e+11,2.613800e+10,...,7.199000e+09,6.661000e+09,1.127320e+11,1.127720e+11,57000000.0,6.118500e+10,1.355990e+11,2.624760e+11,1.980000e+09,1.231635e+12
1,2023-12-31,1.572663e+13,4.095260e+11,5.387588e+12,NaN,2.493040e+11,1.626820e+11,2.737400e+11,2.733640e+11,3.383500e+10,...,3.595000e+09,2.154000e+09,8.652200e+10,6.925800e+10,4000000.0,6.250800e+10,9.530300e+10,1.892160e+11,1.743000e+09,1.126602e+12
2,2022-12-31,1.406728e+13,2.298700e+11,4.958899e+12,NaN,2.251960e+11,1.244790e+11,2.421800e+11,1.836460e+11,2.481500e+10,...,2.465000e+09,1.905000e+09,8.979900e+10,5.180900e+10,11000000.0,6.395500e+10,7.877000e+10,1.614220e+11,1.589000e+09,8.258140e+11
3,2021-12-31,1.258787e+13,2.652290e+11,4.348620e+12,4.786900e+10,1.988400e+11,1.254860e+11,2.195260e+11,3.464300e+10,1.731600e+10,...,5.176000e+09,6.053000e+09,9.803800e+10,5.945100e+10,11000000.0,5.631900e+10,1.548090e+11,9.078200e+10,1.458000e+09,7.955490e+11

### 2.2 Income Statement (利润表)

In [9]:
obb.equity.fundamental.income(symbol=symbol_hk, provider=provider).to_dataframe()

2026-02-04 15:58:07,066 - openbb_akshare.models.income_statement - INFO - Fetching income statement data for 01658 with limit 5 and use_cache=True
2026-02-04 15:58:07,070 - mysharelib.blob_cache - INFO - Loaded cached annual data with length 2 and limit is 5
2026-02-04 15:58:07,070 - mysharelib.blob_cache - INFO - Generating new annual data for 01658...
2026-02-04 15:58:07,071 - openbb_akshare.models.income_statement - INFO - Getting income statement data for 01658 with limit 5
2026-02-04 15:58:07,072 - openbb_akshare.utils.ak_income_statement - INFO - Fetching HK income statement for 01658 with limit 5 and period annual

,period_ending,交易净收益,全面收益总额,其他全面收益,其他全面收益其他项目,其他经营收入,净利息收入,减值及拨备,利息支出,利息收入,...,经营支出总额,经营收入其他项目,经营收入总额,经营溢利,股东应占溢利,营运支出,除税前溢利,除税后溢利,非控股权益应占全面收益总额,非运算项目
0,2024-12-31,4.185000e+09,9.190300e+10,5.187000e+09,5.187000e+09,9.010000e+08,2.861230e+11,2.844500e+10,2.221200e+11,5.082430e+11,...,2.260960e+11,2.500000e+07,3.491330e+11,9.459200e+10,8.647900e+10,2.260960e+11,9.459200e+10,8.671600e+10,237000000.0,5.134300e+11
1,2023-12-31,4.460000e+09,8.671200e+10,2.880000e+08,2.880000e+08,1.418000e+09,2.818030e+11,2.617100e+10,2.165240e+11,4.983270e+11,...,2.251420e+11,1.800000e+07,3.429120e+11,9.159900e+10,8.627000e+10,2.251420e+11,9.159900e+10,8.642400e+10,154000000.0,4.986150e+11
2,2022-12-31,3.673000e+09,7.870500e+10,-6.650000e+09,-6.650000e+09,7.209000e+09,2.735930e+11,3.534700e+10,2.006470e+11,4.742400e+11,...,2.086800e+11,2.843700e+10,3.353910e+11,9.136400e+10,8.522400e+10,2.086800e+11,9.136400e+10,8.535500e+10,131000000.0,5.026740e+11
3,2021-12-31,3.286000e+09,8.586100e+10,9.329000e+09,9.329000e+09,7.450000e+08,2.693820e+11,4.665800e+10,1.821850e+11,4.515670e+11,...,1.909950e+11,NaN,3.191070e+11,8.145400e+10,7.617000e+10,1.909950e+11,8.145400e+10,7.653200e+10,362000000.0,4.608960e+11

### 2.3 Cash Flow Statement (现金流量表)

In [10]:
obb.equity.fundamental.cash(symbol=symbol_hk, provider=provider).to_dataframe().head()

2026-02-04 15:58:19,564 - openbb_akshare.models.cash_flow - INFO - Fetching cash flow data for 01658 with limit 5 and use_cache=True
2026-02-04 15:58:19,567 - mysharelib.blob_cache - INFO - Loaded cached annual data with length 3 and limit is 5
2026-02-04 15:58:19,568 - mysharelib.blob_cache - INFO - Generating new annual data for 01658...
2026-02-04 15:58:19,585 - openbb_akshare.models.cash_flow - INFO - Getting cash flow data for 01658 with limit 5
2026-02-04 15:58:19,586 - openbb_akshare.utils.ak_cash_flow - INFO - Fetching HK cash flow for 01658 with limit 5 and period annual

,period_ending,偿还借款,偿还融资租赁,减:出售资产之溢利,减:利息收入,减:应占附属公司溢利,减:投资收益,减:汇兑收益,加:减值及拨备,加:利息支出,...,经营产生现金,营运资本变动其他项目,营运资金变动前经营溢利,融资业务其他项目,融资业务现金净额,融资前现金净额,购建固定资产,贷款和垫款(增加)减少,除税前溢利(业务利润),非运算项目
0,2024-12-31,2.611600e+11,3.923000e+09,19000000.0,1.417370e+11,25000000.0,3.261700e+10,1.271000e+09,2.844500e+10,5.471000e+09,...,4.010690e+11,-5.019500e+10,-3.577500e+10,NaN,-3.077800e+10,-8.312300e+10,2.035000e+10,-8.037780e+11,9.459200e+10,6.339380e+11
1,2023-12-31,3.351000e+11,3.934000e+09,-10000000.0,1.390810e+11,18000000.0,2.696100e+10,2.520000e+08,2.617100e+10,7.137000e+09,...,2.757960e+11,1.128410e+11,-2.926600e+10,NaN,1.922470e+11,2.090900e+10,1.296300e+10,-9.506910e+11,9.159900e+10,5.072100e+11
2,2022-12-31,2.000000e+10,3.895000e+09,1000000.0,1.284240e+11,3000000.0,2.247900e+10,4.724000e+09,3.534700e+10,3.486000e+09,...,4.875780e+11,1.672100e+11,-1.402100e+10,-5.127300e+10,-3.773700e+10,-3.659300e+10,1.240200e+10,-7.693400e+11,9.136400e+10,1.851730e+11
3,2021-12-31,4.265000e+10,4.012000e+09,-32000000.0,1.276770e+11,NaN,2.368700e+10,-2.432000e+09,4.665800e+10,2.586000e+09,...,1.269000e+11,-1.265430e+11,-9.165000e+09,NaN,5.226300e+10,-7.336000e+10,1.385300e+10,-7.564880e+11,8.145400e+10,3.503260e+11

### 2.4 Key Metrics (关键指标)

In [14]:
obb.equity.fundamental.metrics(symbol=symbol_a, provider=provider).to_dataframe().head()

,symbol,period_ending,fiscal_period,market_cap,股票代码,证券简称,基本每股收益(元),扣非每股收益(元),稀释每股收益(元),每股净资产(元),...,流通股本(股),pe_ratio,市盈率(TTM),市盈率(静),市净率,52周最低,52周最高,股息(TTM),股息率(TTM),发行日期
0,600325,2025-09-30,2025三季报,1.161408e+10,600325.SH,华发股份,0.037,N/A,0.040,6.897,...,"2,752,152,116",85.144,-41.213,12.209,0.612,4.17,5.8544,0.124,2.938,2004-02-25 00:00:00

## 3. 市场分析模型 (Market Analysis Models)
### 3.1 Company News (公司新闻)

In [15]:
obb.news.company(symbol_a, provider=provider).to_dataframe().head()

,title,url
date,,
2026-01-30 20:22:06,华发股份预计2025年亏损70亿元至90亿元,http://finance.eastmoney.com/a/202601303637262...
2026-01-30 21:06:38,华发股份预计2025年净亏损70亿—90亿元,http://finance.eastmoney.com/a/202601303637299...
2026-01-31 07:05:20,华金证券党委书记、总裁燕文波： 坚守功能性定位 打造差异化竞争力,http://finance.eastmoney.com/a/202601313637474...
2026-01-31 07:50:42,华发股份：融资净买入359.82万元，融资余额6.92亿元,http://stock.eastmoney.com/a/20260131363762486...
2026-01-31 11:26:58,华发股份：加快转型应对行业调整,http://finance.eastmoney.com/a/202601313637734...

### 3.2 Business Analysis (业务分析)

In [18]:
obb.akshare.business_analysis(symbol=symbol_a, provider=provider).to_dataframe().head()

,symbol,report_date,main_composition,category_type,main_revenue,revenue_ratio,main_cost,cost_ratio,main_profit,profit_ratio,gross_margin,code
0,600325.SS,2025-09-30,房地产开发,按行业分类,4.688954e+10,0.906074,3.986067e+10,0.898329,7.028870e+09,0.952651,0.149903,600325
1,600325.SS,2025-09-30,其他业务,按行业分类,4.860711e+09,0.093926,4.511359e+09,0.101671,3.493517e+08,0.047349,0.071873,600325
2,600325.SS,2025-09-30,其中:住宅,按行业分类,4.401008e+10,0.850432,3.705148e+10,0.835019,6.958600e+09,0.943127,0.158114,600325
3,600325.SS,2025-09-30,其中:商业、办公,按行业分类,2.879464e+09,0.055642,2.809193e+09,0.063310,7.027040e+07,0.009524,0.024404,600325
4,600325.SS,2025-09-30,房地产开发,按产品分类,4.688954e+10,0.906074,3.986067e+10,0.898329,7.028870e+09,0.952651,0.149903,600325

### 3.3 Price Performance (价格表现)

In [16]:
obb.equity.price.performance(symbol=symbols, provider=provider).to_dataframe().head()

2026-02-04 11:11:22,584 - openbb_akshare.utils.helpers - INFO - Listing date for 601919 is 1182787200000.0.
2026-02-04 11:11:22,864 - openbb_akshare.utils.helpers - WARNING - Cache for 601919 is not up-to-date. Last date in cache: 2026-01-21, expected: 2026-02-03.
2026-02-04 11:11:26,514 - openbb_akshare.utils.helpers - INFO - Getting equity 601919 historical data from cache...
2026-02-04 11:11:26,804 - openbb_akshare.utils.helpers - INFO - Listing date for 600519 is 2001-08-26 16:00:00.
2026-02-04 11:11:27,246 - openbb_akshare.utils.helpers - WARNING - Cache for 600519 is not up-to-date. Last date in cache: NaT, expected: 2026-02-03.
2026-02-04 11:11:27,678 - openbb_akshare.utils.helpers - INFO - Getting equity 600519 historical data from cache...
2026-02-04 11:11:27,682 - openbb_akshare.utils.helpers - INFO - Listing date for 000001 is 670608000000.0.
2026-02-04 11:11:28,155 - openbb_akshare.utils.helpers - WARNING - Cache for 000001 is not up-to-date. Last date in cache: 2026-01-30, expected: 2026-02-03.
2026-02-04 11:11:28,631 - openbb_akshare.utils.helpers - INFO - Getting equity 000001 historical data from cache...
2026-02-04 11:11:28,922 - openbb_akshare.utils.helpers - INFO - Listing date for 00300 is 2024-09-16 16:00:00.
2026-02-04 11:11:29,634 - openbb_akshare.utils.helpers - WARNING - Cache for 00300 is not up-to-date. Last date in cache: 2026-01-23, expected: 2026-02-03.
2026-02-04 11:11:29,911 - openbb_akshare.utils.helpers - INFO - Getting equity 00300 historical data from cache...

,symbol,one_day,wtd,one_week,mtd,one_month,qtd,three_month,six_month,ytd,one_year,two_year,three_year,four_year,five_year,ten_year,max
0,601919,0.000049,0.000049,-0.000180,0.000049,-0.000501,-0.000456,-0.000790,-0.000925,-0.000456,0.000092,0.004163,0.003315,-0.001397,0.003415,0.016679,-0.001319
1,600519,0.000336,0.000336,0.000259,0.000336,0.000328,0.000343,0.000290,0.000207,0.000343,0.000507,-0.001200,-0.001783,-0.002104,-0.003774,0.063595,0.404886
2,000001,-0.000018,-0.000018,-0.000109,-0.000018,-0.000711,-0.000574,-0.000615,-0.001187,-0.000574,-0.000466,0.001198,-0.002257,-0.003386,-0.005629,0.001073,-0.007788
3,00300,0.000152,0.000152,0.000093,0.000152,-0.000017,-0.000252,0.000104,0.000984,-0.000252,0.001982,0.004729,0.004729,0.004729,0.004729,0.004729,0.004729

## 4. 基金相关模型 (Fund Models)
### 4.1 ETF Holdings (ETF 持仓)

In [ ]:
obb.akshare.etf_holdings(symbol="159919", provider=provider).to_dataframe().head()

### 4.2 ETF Search (ETF 搜索)

In [17]:
obb.etf.search(provider='akshare').to_dataframe().head()

   symbol        name
0  000001      华夏成长混合
1  000002  华夏成长混合(后端)
2  000003    中海可转债债券A
3  000004    中海可转债债券C
4  000005  嘉实增强信用定期债券

### 4.3 Fund Holdings (基金持仓)

In [ ]:
obb.akshare.fund_holdings(symbol="000011", provider=provider).to_dataframe().head()

## 5. 货币相关模型 (Currency Models)
### 5.1 Currency Historical (货币历史价格)

In [19]:
obb.currency.price.historical(symbol='EURUSD', provider=provider).to_dataframe().head()

             open   high    low  close  change  symbol   name
date
1999-01-01  1.174  1.180  1.166  1.180    0.00  EURUSD  欧元兑美元
1999-01-04  1.175  1.190  1.174  1.179    1.36  EURUSD  欧元兑美元
1999-01-05  1.179  1.184  1.177  1.182    0.59  EURUSD  欧元兑美元
1999-01-06  1.182  1.182  1.172  1.175    0.85  EURUSD  欧元兑美元
1999-01-07  1.175  1.177  1.156  1.166    1.79  EURUSD  欧元兑美元

### 5.2 Currency Snapshots (货币快照)

In [21]:
obb.currency.snapshots(provider=provider).to_dataframe().head()

OpenBBError:
[Unexpected Error] -> ProxyError -> HTTPSConnectionPool(host='push2.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/clist/get?np=1&fltt=2&invt=2&fs=m%3A119%2Cm%3A120%2Cm%3A133&fields=f12%2Cf13%2Cf14%2Cf1%2Cf2%2Cf4%2Cf3%2Cf152%2Cf17%2Cf18%2Cf15%2Cf16&fid=f3&pn=1&pz=100&po=1&dect=1&wbp2u=%7C0%7C0%7C0%7Cweb (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

## 6. 指数相关模型 (Index Models)
### 6.1 Available Indices (可用指数)

In [22]:
obb.index.available(provider=provider).to_dataframe().head()

   symbol  name currency publish_date
0  000001  上证指数      CNY   1991-07-15
1  000002  A股指数      CNY   1992-02-21
2  000003  B股指数      CNY   1992-02-21
3  000004  工业指数      CNY   1993-05-03
4  000005  商业指数      CNY   1993-05-03